spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:h2:file:~/springboot;AUTO_SERVER=TRUE
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
server:
  port: 3000

