spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:h2:file:./src/data/photos
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

server:
  port: 3000

logging:
  file:
    name: photos.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: ERROR
    org.springframework.jdbc: DEBUG
    com.example.demo.*: INFO




